### ISSUE TITLE
Bug: using column named Group results in exception on inserts

### ISSUE THREAD

**Issue by brgrz** [MightyOrm/Mighty#8]
Table has a column named Group. When inserting new records exception occurs. Could it have something to do with the GROUP BY sentence in SQL?

```
System.Data.SqlClient.SqlException
  HResult=0x80131904
  Message=Incorrect syntax near the keyword 'Group'.
  Source=Core .Net SqlClient Data Provider
  StackTrace:
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Mighty.MightyOrm`1.Execute(DbCommand command, DbConnection connection)
   at Mighty.MightyOrm`1.ActionOnItem(Object& modified, OrmAction originalAction, Object item, DbConnection connection)
   at Mighty.MightyOrm`1.ActionOnItemsWithOutput(OrmAction action, DbConnection connection, IEnumerable`1 items)
   at Mighty.MightyOrm`1.Insert(Object item)
```

**Comment by mikebeaton** [comment]
I'm pretty sure Massive would have done this too, it doesn't by default quote column names (e.g. `[Group]` instead of `Group` is what would be required for SQL Server). In Mighty you could write a `SqlNamingMapper` which overrides `ColumnNameMapping` only, to do the required quoting.

**Comment by mikebeaton** [comment]
@brgrz Does this provide you with a workaround? (Re-open if not.)

As I say, Massive would have had this problem too.

I *could* update the code to always quote all DB names (although IIRC there are cases where exactly which quote characters are needed depends on context, so this might be non-trivial).

It's pretty much a corner case - at least seemingly the same behaviour wasn't a real problem in Massive. And Mighty does provide a work-around (other than changing the code yourself!), as described above.

**Comment by brgrz** [comment]
No problem, I just changed the name of the column and it's fine.
